name: Build Node.js Project to EXE

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Updated to the latest version
      with:
        repository: 'Genshin-Impact-Wish-Simulator/Genshin-Impact-Wish-Simulator'

    - name: Setup Node.js
      uses: actions/setup-node@v3  # Updated to use Node.js 20
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Copy Static Files
      run: |
        mkdir -p ../electron-static/static  # Ensure the target directory exists
        cp -r .vercel/static/* ../electron-static/static  # Updated to ensure correctness

    - name: Install Electron Dependencies and Build
      run: |
        cd electron-static
        npm install
        npm run build  # Build for the current OS
        npm run build-win  # Build for Windows

    # Optionally, add steps to upload the EXE file as an artifact or to a release
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-exe
        path: electron-static/dist/*.exe
